(function () {
  const translations = {
    tr:{kicker:"NFC kart talebi",pending:"Beklemede",approved:"Onaylandı",rejected:"Değişiklik gerekli",pendingTitle:"Talebiniz inceleniyor.",approvedTitle:"Tasarımınız onaylandı.",rejectedTitle:"Tasarım için değişiklik istendi.",pendingMessage:"Tasarımınız AuraDigital paneline ulaştı. Ödeme ve tasarım onayından sonra durum yeşile dönecek.",approvedMessage:"Ödeme ve tasarım onayı tamamlandı. Kartınız üretim için hazır.",rejectedMessage:"AuraDigital tasarımda bir düzenleme istemiş olabilir. Ayrıntılar için sizinle iletişime geçeceğiz.",business:"İşletme",type:"Kart türü",payment:"Ödeme",updated:"Son güncelleme",paid:"Ödendi",unpaid:"Bekliyor",reviews:"Google yorum",website:"Web sitesi",refresh:"Durumu yenile",newRequest:"Yeni tasarım hazırla",missing:"Geçerli bir talep bağlantısı bulunamadı.",notFound:"Talep bulunamadı veya bağlantı geçersiz.",loading:"Yükleniyor…"},
    en:{kicker:"NFC card request",pending:"Pending",approved:"Approved",rejected:"Changes requested",pendingTitle:"Your request is being reviewed.",approvedTitle:"Your design is approved.",rejectedTitle:"Design changes were requested.",pendingMessage:"Your design reached the AuraDigital dashboard. It turns green after payment and design approval.",approvedMessage:"Payment and design approval are complete. Your card is ready for production.",rejectedMessage:"AuraDigital may need a design adjustment. We will contact you with the details.",business:"Business",type:"Card type",payment:"Payment",updated:"Last update",paid:"Paid",unpaid:"Pending",reviews:"Google reviews",website:"Website",refresh:"Refresh status",newRequest:"Create another design",missing:"No valid request link was found.",notFound:"The request was not found or the link is invalid.",loading:"Loading…"},
    ar:{kicker:"طلب بطاقة NFC",pending:"قيد الانتظار",approved:"تمت الموافقة",rejected:"التعديل مطلوب",pendingTitle:"طلبك قيد المراجعة.",approvedTitle:"تمت الموافقة على التصميم.",rejectedTitle:"طُلب تعديل التصميم.",pendingMessage:"وصل تصميمك إلى لوحة AuraDigital. يصبح أخضر بعد تأكيد الدفع والتصميم.",approvedMessage:"تم تأكيد الدفع والتصميم. بطاقتك جاهزة للإنتاج.",rejectedMessage:"قد يحتاج التصميم إلى تعديل وسنتواصل معك بالتفاصيل.",business:"النشاط",type:"نوع البطاقة",payment:"الدفع",updated:"آخر تحديث",paid:"تم الدفع",unpaid:"قيد الانتظار",reviews:"تقييم Google",website:"الموقع",refresh:"تحديث الحالة",newRequest:"إنشاء تصميم جديد",missing:"لا يوجد رابط طلب صالح.",notFound:"الطلب غير موجود أو الرابط غير صالح.",loading:"جارٍ التحميل…"}
  };
  const params = new URLSearchParams(location.search);
  const language = ["tr","en","ar"].includes(params.get("lang")) ? params.get("lang") : (() => { try { const stored=localStorage.getItem("aura-nfc-lang"); return ["tr","en","ar"].includes(stored)?stored:"tr"; } catch { return "tr"; } })();
  const text = translations[language];
  const requestId = params.get("id") || (() => { try { return localStorage.getItem("aura-nfc-last-request"); } catch { return ""; } })();
  document.documentElement.lang=language;document.documentElement.dir=language==="ar"?"rtl":"ltr";
  const byId=(id)=>document.getElementById(id);
  function baseCopy(){byId("statusKicker").textContent=text.kicker;byId("businessLabel").textContent=text.business;byId("typeLabel").textContent=text.type;byId("paymentLabel").textContent=text.payment;byId("updatedLabel").textContent=text.updated;byId("refreshButton").textContent=text.refresh;byId("newRequestLink").textContent=text.newRequest;}
  async function load(){const notice=byId("statusNotice");if(!requestId){notice.className="form-notice error";notice.textContent=text.missing;return}byId("refreshButton").disabled=true;notice.className="form-notice";notice.textContent=text.loading;try{const response=await fetch(`/api/nfc/requests/${encodeURIComponent(requestId)}`,{headers:{Accept:"application/json"}});const data=await response.json().catch(()=>({}));if(!response.ok)throw new Error(text.notFound);const request=data.request;const status=["approved","rejected"].includes(request.status)?request.status:"pending";byId("statusSignal").className=`status-signal ${status}`;byId("statusLabel").textContent=text[status];byId("statusTitle").textContent=text[`${status}Title`];byId("statusMessage").textContent=text[`${status}Message`];byId("businessValue").textContent=request.businessName;byId("typeValue").textContent=text[request.cardType]||request.cardType;byId("paymentValue").textContent=request.paymentStatus==="paid"?text.paid:text.unpaid;byId("updatedValue").textContent=new Intl.DateTimeFormat(language,{dateStyle:"medium",timeStyle:"short"}).format(new Date(request.updatedAt));byId("requestDetails").hidden=false;notice.textContent=""}catch(error){notice.className="form-notice error";notice.textContent=error.message||text.notFound}finally{byId("refreshButton").disabled=false}}
  baseCopy();byId("refreshButton").addEventListener("click",load);load();
})();
