const CATEGORIES=[
{id:'coffee',label:'Coffee',icon:'☕',templates:[
{id:'coffee-roast',name:'Roast House',desc:'Warm editorial coffee shop with rich photography.',image:'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?auto=format&fit=crop&w=1200&q=80',base:'espresso',color:'#9b4a2c'},
{id:'coffee-minimal',name:'Daily Brew',desc:'Bright minimal café built around menu and location.',image:'https://images.unsplash.com/photo-1501339847302-ac426a4a7cbb?auto=format&fit=crop&w=1200&q=80',base:'nova-menu',color:'#486447'},
{id:'coffee-night',name:'After Hours',desc:'Dark modern specialty coffee design.',image:'https://images.unsplash.com/photo-1445116572660-236099ec97a0?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#c27b3a'}]},
{id:'restaurant',label:'Restaurant',icon:'🍽️',templates:[
{id:'restaurant-bistro',name:'Table No. 7',desc:'Elegant bistro layout with dishes and booking CTA.',image:'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?auto=format&fit=crop&w=1200&q=80',base:'nova-menu',color:'#9a3d32'},
{id:'restaurant-luxe',name:'Maison',desc:'Luxury dining look for premium restaurants.',image:'https://images.unsplash.com/photo-1552566626-52f8b828add9?auto=format&fit=crop&w=1200&q=80',base:'espresso',color:'#6f5a37'},
{id:'restaurant-street',name:'Street Kitchen',desc:'Bold fast-food and casual restaurant template.',image:'https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#d95e2f'}]},
{id:'beauty',label:'Beauty',icon:'✦',templates:[
{id:'beauty-soft',name:'Studio Aura',desc:'Soft premium salon and beauty studio layout.',image:'https://images.unsplash.com/photo-1560066984-138dadb4c035?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#b77678'},
{id:'beauty-editorial',name:'Muse',desc:'Editorial beauty template with large imagery.',image:'https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=1200&q=80',base:'mono-portfolio',color:'#8d6070'},
{id:'beauty-dark',name:'Noir Studio',desc:'Dark luxury barber, nail or beauty studio.',image:'https://images.unsplash.com/photo-1503951914875-452162b0f3f1?auto=format&fit=crop&w=1200&q=80',base:'espresso',color:'#8e734c'}]},
{id:'fitness',label:'Fitness',icon:'⚡',templates:[
{id:'fitness-power',name:'Forge',desc:'High-energy gym landing page with strong CTA.',image:'https://images.unsplash.com/photo-1534438327276-14e5300c3a48?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#e4542d'},
{id:'fitness-clean',name:'Form',desc:'Clean trainer, pilates and wellness layout.',image:'https://images.unsplash.com/photo-1518611012118-696072aa579a?auto=format&fit=crop&w=1200&q=80',base:'mono-portfolio',color:'#4f7762'},
{id:'fitness-neon',name:'Pulse',desc:'Modern dark gym design with energetic accents.',image:'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&w=1200&q=80',base:'nova-menu',color:'#8fae33'}]},
{id:'services',label:'Services',icon:'◼',templates:[
{id:'services-local',name:'Local Pro',desc:'Trust-first site for repair, moving and local services.',image:'https://images.unsplash.com/photo-1581578731548-c64695cc6952?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#376d85'},
{id:'services-corporate',name:'Clearline',desc:'Professional corporate service presentation.',image:'https://images.unsplash.com/photo-1497366754035-f200968a6e72?auto=format&fit=crop&w=1200&q=80',base:'mono-portfolio',color:'#42566b'},
{id:'services-bold',name:'Fixr',desc:'Bold conversion-focused service business template.',image:'https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&w=1200&q=80',base:'espresso',color:'#c16831'}]},
{id:'portfolio',label:'Portfolio',icon:'◎',templates:[
{id:'portfolio-grid',name:'Frame',desc:'Visual grid for photographers, designers and creators.',image:'https://images.unsplash.com/photo-1524758631624-e2822e304c36?auto=format&fit=crop&w=1200&q=80',base:'mono-portfolio',color:'#5d59a6'},
{id:'portfolio-personal',name:'Profile',desc:'Personal brand and freelancer portfolio.',image:'https://images.unsplash.com/photo-1521737711867-e3b97375f902?auto=format&fit=crop&w=1200&q=80',base:'local-pro',color:'#476b6c'},
{id:'portfolio-studio',name:'Studio',desc:'Agency-style portfolio with strong case-study look.',image:'https://images.unsplash.com/photo-1497366811353-6870744d04b2?auto=format&fit=crop&w=1200&q=80',base:'nova-menu',color:'#a14e37'}]}];
const PAYMENTS=[
{id:'simple',name:'Simple Pay',desc:'Clean total + payment button.',mock:'₺ 2,500 → Pay'},
{id:'invoice',name:'Invoice',desc:'Itemized professional payment view.',mock:'Invoice #QS-01'},
{id:'deposit',name:'Deposit',desc:'Show deposit now and balance later.',mock:'30% Deposit'}];
let category=CATEGORIES[0],template=category.templates[0],payment=PAYMENTS[0];
const $=s=>document.querySelector(s);const tabs=$('#categoryTabs'),grid=$('#templateGrid'),payGrid=$('#paymentGrid'),form=$('#quicksiteForm');
function renderCategories(){tabs.innerHTML=CATEGORIES.map(c=>`<button class="category-btn ${c.id===category.id?'active':''}" data-cat="${c.id}"><span>${c.icon}</span>${c.label}</button>`).join('');tabs.querySelectorAll('button').forEach(b=>b.onclick=()=>{category=CATEGORIES.find(c=>c.id===b.dataset.cat);template=category.templates[0];renderAll()})}
function renderTemplates(){grid.innerHTML=category.templates.map(t=>`<article class="template-card ${t.id===template.id?'active':''}" data-template="${t.id}"><div class="template-shot" style="background-image:url('${t.image}')"><div class="mini"><small>${category.label.toUpperCase()}</small><strong>${t.name}</strong></div></div><div class="template-copy"><strong>${t.name}</strong><p>${t.desc}</p></div></article>`).join('');grid.querySelectorAll('.template-card').forEach(el=>el.onclick=()=>{template=category.templates.find(t=>t.id===el.dataset.template);form.primaryColor.value=template.color;renderTemplates();renderPreview();updatePill()})}
function renderPayments(){payGrid.innerHTML=PAYMENTS.map(p=>`<div class="payment-card ${p.id===payment.id?'active':''}" data-pay="${p.id}"><div class="pay-mock">${p.mock}</div><strong>${p.name}</strong><small>${p.desc}</small></div>`).join('');payGrid.querySelectorAll('.payment-card').forEach(el=>el.onclick=()=>{payment=PAYMENTS.find(p=>p.id===el.dataset.pay);renderPayments();renderPreview()})}
function updatePill(){$('#selectedPill').textContent=`${category.label} · ${template.name}`}
function addOffer(values={}){const el=document.createElement('div');el.className='offer-row';el.innerHTML=`<input class="of-name" placeholder="Item / service" value="${values.name||''}"><input class="of-desc" placeholder="Short description" value="${values.description||''}"><input class="of-price" placeholder="Price" value="${values.price||''}"><button class="remove-offer" type="button">×</button>`;el.querySelector('.remove-offer').onclick=()=>{el.remove();renderPreview()};el.querySelectorAll('input').forEach(i=>i.addEventListener('input',renderPreview));$('#offers').appendChild(el)}
$('#addOffer').onclick=()=>addOffer();addOffer({name:'Signature offer',description:'Your best-selling product or service',price:'₺ —'});addOffer({name:'Second offer',description:'Another popular choice',price:'₺ —'});
function values(){const fd=new FormData(form);return Object.fromEntries(fd.entries())}
function offers(){return [...document.querySelectorAll('.offer-row')].map(r=>({name:r.querySelector('.of-name').value.trim(),description:r.querySelector('.of-desc').value.trim(),price:r.querySelector('.of-price').value.trim()})).filter(x=>x.name)}
function renderPreview(){const v=values(),items=offers();const hero=v.heroImageUrl||template.image;const color=v.primaryColor||template.color;const name=v.businessName||template.name;const tag=v.tagline||template.desc;$('#livePreview').innerHTML=`<section class="pv-hero" style="background-image:url('${hero.replaceAll("'",'')}')"><small>${category.label.toUpperCase()} · ${template.name.toUpperCase()}</small><h3>${escapeHtml(name)}</h3><p>${escapeHtml(tag)}</p></section><div class="pv-content"><a class="pv-btn" style="background:${color}">Contact us</a><div class="pv-items">${(items.length?items:[{name:'Your offer',description:'Add your services or products',price:''}]).slice(0,3).map(x=>`<div class="pv-item"><b>${escapeHtml(x.name)} ${x.price?`· ${escapeHtml(x.price)}`:''}</b><small>${escapeHtml(x.description)}</small></div>`).join('')}</div><div class="pv-pay"><strong>${payment.name}</strong><small>${payment.desc}</small></div></div>`}
function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]))}
form.addEventListener('input',renderPreview);
form.addEventListener('submit',async e=>{e.preventDefault();const v=values();const status=$('#submitStatus');status.textContent='Sending your QuickSite request…';const marker=`[QUICKSITE V2]\nCategory: ${category.id}\nDesign: ${template.id}\nPayment layout: ${payment.id}\n\n${v.requestMessage||''}`;const payload={templateId:template.base,industry:`${category.id}:${template.id}`,businessName:v.businessName,slug:v.slug,tagline:v.tagline,description:v.description,primaryColor:v.primaryColor,heroImageUrl:v.heroImageUrl,logoUrl:v.logoUrl,galleryUrls:[v.gallery1,v.gallery2,v.gallery3].filter(Boolean),offers:offers(),phone:v.phone,whatsapp:v.whatsapp,email:v.email,address:v.address,instagram:v.instagram,workingHours:v.workingHours,contactName:v.contactName,language:v.language,requestMessage:marker,primaryCta:'Contact us'};try{const r=await fetch('/api/quicksite',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await r.json().catch(()=>({}));if(!r.ok)throw new Error(data.error||'Request failed');status.textContent=`✓ Request received. Project: ${data.project?.slug||data.project?.id||'created'}`;status.style.color='#287346'}catch(err){status.textContent=err.message;status.style.color='#a0382c'}});
function renderAll(){renderCategories();renderTemplates();renderPayments();updatePill();form.primaryColor.value=template.color;renderPreview()}renderAll();