-- Additive migration: existing clients, menus, NFC requests and admin access remain intact.
CREATE TABLE IF NOT EXISTS project_catalog (id INTEGER PRIMARY KEY CHECK(id=1), catalog_json TEXT NOT NULL, revision INTEGER NOT NULL DEFAULT 1, updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS studio_projects (sequence INTEGER PRIMARY KEY AUTOINCREMENT, id TEXT NOT NULL UNIQUE, client_json TEXT NOT NULL, configuration_json TEXT NOT NULL, quote_json TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'NEW REQUEST', notes TEXT NOT NULL DEFAULT '', payment_url TEXT NOT NULL DEFAULT '', preview_url TEXT NOT NULL DEFAULT '', paid REAL NOT NULL DEFAULT 0, revision INTEGER NOT NULL DEFAULT 1, submission_key TEXT NOT NULL UNIQUE, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE INDEX IF NOT EXISTS studio_projects_created ON studio_projects(created_at DESC);
CREATE TABLE IF NOT EXISTS project_events (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES studio_projects(id), status TEXT NOT NULL, actor TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_files (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES studio_projects(id), name TEXT NOT NULL, mime TEXT NOT NULL, bytes BLOB NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_emails (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES studio_projects(id), event TEXT NOT NULL, state TEXT NOT NULL DEFAULT 'queued', message_id TEXT NOT NULL DEFAULT '', attempts INTEGER NOT NULL DEFAULT 0, created_at TEXT NOT NULL DEFAULT (datetime('now')), updated_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_access (id TEXT PRIMARY KEY, project_id TEXT NOT NULL REFERENCES studio_projects(id), token_hash TEXT NOT NULL UNIQUE, kind TEXT NOT NULL CHECK(kind IN ('invite','session')), expires_at TEXT NOT NULL, created_at TEXT NOT NULL DEFAULT (datetime('now')));
CREATE TABLE IF NOT EXISTS project_rate_limits (key TEXT PRIMARY KEY, created_at TEXT NOT NULL DEFAULT (datetime('now')));
