import {themes} from './themes.js?v=20260917-3';
const theme=themes.find(t=>t.slug===document.body.dataset.theme);
if(!theme) throw new Error('Unknown invitation theme');
document.body.className=`${theme.slug} ${theme.kind} ${theme.dark?'dark':''}`;
for(const [key,value] of Object.entries({paper:theme.paper,ink:theme.color,accent:theme.accent})) document.body.style.setProperty(`--${key}`,value);
document.title=`${theme.name} — Invitation preview | AuraWeddings`;
const root=document.querySelector('#invitation');
root.innerHTML=`<div class="progress" aria-hidden="true"></div>
<div class="invitation-gate" role="dialog" aria-modal="true" aria-label="Open wedding invitation">
  <div class="gate-glow" aria-hidden="true"></div>
  <div class="wedding-card">
    <span class="card-kicker">Together with their families</span>
    <div class="card-photo-wrap"><img src="${theme.image}" alt="Amelia and Adam in the ${theme.name} invitation"><span class="photo-ring" aria-hidden="true">A <i>&amp;</i> A</span></div>
    <p class="save-date">Save the date</p><h1>Amelia <i>&amp;</i> Adam</h1>
    <div class="card-divider" aria-hidden="true"><span>♡</span></div>
    <time datetime="2027-06-29T18:00:00+03:00">29 · JUNE · 2027</time>
    <button class="open-card" aria-label="Open the wedding invitation"><span>Open invitation</span><b>↓</b></button>
    <span class="floral-corner floral-one" aria-hidden="true"></span><span class="floral-corner floral-two" aria-hidden="true"></span>
  </div>
  <p class="gate-instruction">Tap to enter our celebration</p>
</div>
<header class="topbar"><a href="/aura-weddings#themes">← AuraWeddings</a><span class="demo-label">${theme.name} · DEMO</span></header>
<section class="cover" aria-label="Invitation cover"><video class="cover-video" autoplay muted loop playsinline poster="/weddings/art/garden.webp" aria-hidden="true"><source src="https://assets.mixkit.co/videos/40601/40601-720.mp4" type="video/mp4"></video><div class="cover-shade" aria-hidden="true"></div><div class="sparkles" aria-hidden="true"></div><div class="cover-frame" aria-hidden="true"></div><div class="curtain-panel" aria-hidden="true"></div><div class="curtain-panel right" aria-hidden="true"></div><div class="cover-copy"><p class="eyeline">Together with our families</p><h1>Amelia<span>&amp;</span>Adam</h1><p class="cover-date">29 · JUNE · 2027</p><button class="seal" aria-label="Continue through invitation">Explore our day</button><span class="open-label">A little invitation. A lifetime of love.</span><p class="scroll-hint">Scroll to explore our celebration</p></div></section>
<main class="invitation"><section id="welcome" class="intro reveal"><p class="eyeline">With full hearts</p><h2>We saved you<br><em>a place in our story.</em></h2><div class="ornament"></div><p>Two paths, one beautiful beginning. We would be delighted to have you beside us as we celebrate our wedding.</p><div class="date-block"><span class="side">Tuesday<br>June</span><span class="day serif">29</span><span class="side">2027<br>18:00</span></div><p class="eyeline">A celebration by the Mediterranean</p></section>
<section class="story"><img class="art-photo reveal" src="/weddings/art/garden.webp" alt="Illustrative Mediterranean wedding garden overlooking the sea" width="640" height="960" loading="lazy"><div class="story-copy reveal"><p class="eyeline">Our next chapter</p><h2>A thousand<br>little moments.<br><em>One forever.</em></h2><p>From our first conversation to the adventures that followed, it has always been the little things. Now we are ready for our favourite adventure yet, surrounded by the people we love.</p><p class="serif quote">“Home is wherever<br>we are together.”</p></div></section>
<section class="memories reveal"><p class="eyeline">A glimpse of us</p><h2>Every love story<br><em>deserves to be felt.</em></h2><div class="photo-ribbon">
<figure class="couple-photo portrait"><img src="https://images.unsplash.com/photo-1519741497674-611481863552?auto=format&fit=crop&w=1000&q=82" alt="Wedding couple sharing a quiet moment" loading="lazy"><figcaption>The beginning of forever</figcaption></figure>
<figure class="couple-photo landscape"><img src="https://images.unsplash.com/photo-1519225421980-715cb0215aed?auto=format&fit=crop&w=1200&q=82" alt="Newly married couple outdoors" loading="lazy"><figcaption>Two hearts · one home</figcaption></figure>
<figure class="couple-photo portrait"><img src="https://images.unsplash.com/photo-1606800052052-a08af7148866?auto=format&fit=crop&w=1000&q=82" alt="Hands of a wedding couple" loading="lazy"><figcaption>Written in the little things</figcaption></figure>
</div></section>
<section class="moment reveal"><p class="eyeline">Until we say “I do”</p><h2>Every moment brings us closer.</h2><div class="countdown" aria-label="Countdown to the example wedding"><div><b data-unit="days">—</b><span>Days</span></div><div><b data-unit="hours">—</b><span>Hours</span></div><div><b data-unit="minutes">—</b><span>Minutes</span></div><div><b data-unit="seconds">—</b><span>Seconds</span></div></div></section>
<section class="details reveal"><p class="eyeline">The celebration</p><h2>One beautiful evening.</h2><div class="schedule"><article><time>18:00</time><h3>The welcome</h3><p>Arrive, settle in and raise a glass with us.</p></article><article><time>18:30</time><h3>The vows</h3><p>A promise to each other, with our favourite people.</p></article><article><time>20:00</time><h3>Dinner & dancing</h3><p>Good food, great company, and one last song.</p></article></div></section>
<section class="venue reveal"><div class="venue-copy"><p class="eyeline">Wedding reception venue</p><h2>The garden<br><em>by the sea.</em></h2><h3>Four Seasons Hotel Bosphorus</h3><p>Çırağan Cad. No:28, Beşiktaş, Istanbul</p><div class="venue-actions"><a class="link-button" href="https://www.google.com/maps/dir/?api=1&destination=Four+Seasons+Hotel+Bosphorus+Istanbul" target="_blank" rel="noopener">Get directions ↗</a><a class="link-button ghost" href="https://www.google.com/calendar/render?action=TEMPLATE&text=Amelia+%26+Adam+Wedding&dates=20270629T150000Z/20270629T210000Z&location=Four+Seasons+Hotel+Bosphorus%2C+Istanbul" target="_blank" rel="noopener">Add to calendar</a></div><p><small>Demo location — every invitation will use the couple's real venue.</small></p></div><div class="map-frame"><iframe title="Map showing Four Seasons Hotel Bosphorus" src="https://www.google.com/maps?q=Four+Seasons+Hotel+Bosphorus+Istanbul&output=embed" loading="lazy" referrerpolicy="no-referrer-when-downgrade" allowfullscreen></iframe><span class="map-pin" aria-hidden="true">♡</span></div></section>
<section class="closing reveal"><p class="eyeline">Your presence is our favourite gift</p><h2>Here’s to love.<br><em>And to you.</em></h2><p>We cannot wait to celebrate together. This preview can be personalised with your names, photographs, venue and chosen music.</p><a class="link-button" href="/contact?service=auraweddings&theme=${theme.slug}">Choose ${theme.name} →</a><br><a class="link-button" href="/aura-weddings#themes">Explore all ten themes</a></section></main>
<footer class="footer">An invitation by <a href="/aura-weddings">AuraWeddings</a> · ${theme.name}<br>Demo artwork · original ambient melody</footer><button class="sound" aria-pressed="false" aria-label="Play background music">♫ Music off</button>`;
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const gate=document.querySelector('.invitation-gate');
const openExperience=()=>{if(document.body.classList.contains('experience-open'))return;document.body.classList.add('experience-open','opened');gate?.setAttribute('aria-hidden','true');setMusic(true);setTimeout(()=>gate?.remove(),reduced?80:1900);};
document.querySelector('.open-card')?.addEventListener('click',openExperience);
gate?.addEventListener('click',e=>{if(e.target===gate||e.target.classList.contains('gate-glow'))openExperience();});
addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!document.body.classList.contains('experience-open')){e.preventDefault();openExperience();}});
for(let i=0;i<18;i++){const star=document.createElement('i');star.style.setProperty('--x',Math.random()*100+'%');star.style.setProperty('--y',Math.random()*100+'%');star.style.setProperty('--d',(2+Math.random()*5)+'s');star.style.setProperty('--delay',(-Math.random()*6)+'s');document.querySelector('.sparkles')?.append(star);}
if(!reduced){addEventListener('pointermove',e=>{document.documentElement.style.setProperty('--mx',(e.clientX/innerWidth-.5).toFixed(3));document.documentElement.style.setProperty('--my',(e.clientY/innerHeight-.5).toFixed(3));},{passive:true});}
if(!reduced&&'IntersectionObserver' in window){document.body.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');observer.unobserve(e.target)}}),{threshold:.08});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));}
const wedding=new Date('2027-06-29T18:00:00+03:00').getTime();
function countdown(){let s=Math.max(0,Math.floor((wedding-Date.now())/1000));const units={days:Math.floor(s/86400),hours:Math.floor(s/3600)%24,minutes:Math.floor(s/60)%60,seconds:s%60};for(const [key,value] of Object.entries(units)) document.querySelector(`[data-unit="${key}"]`).textContent=String(value).padStart(2,'0');}
countdown();setInterval(countdown,1000);
let audio,master,timer,playing=false,step=0;
const sound=document.querySelector('.sound');
const notes=[0,7,12,16,14,12,7,4,0,7,12,19,16,14,12,7];
const base=[196,220,174.61,196,261.63,164.81,174.61,220,196,146.83][themes.indexOf(theme)];
function tone(){if(!audio||!playing)return;const now=audio.currentTime;const osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=base*Math.pow(2,notes[step++%notes.length]/12);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.12,now+.025);gain.gain.exponentialRampToValueAtTime(.0001,now+2.5);osc.connect(gain);gain.connect(master);osc.start(now);osc.stop(now+2.6);osc.onended=()=>{osc.disconnect();gain.disconnect()};}
async function setMusic(on){try{if(on){const Audio=window.AudioContext||window.webkitAudioContext;if(!Audio)throw new Error('Audio unavailable');if(!audio){audio=new Audio();master=audio.createGain();master.gain.value=.32;master.connect(audio.destination);}await audio.resume();playing=true;tone();clearInterval(timer);timer=setInterval(tone,620);}else{playing=false;clearInterval(timer);if(audio)await audio.suspend();}sound.textContent=playing?'Ⅱ Music on':'♫ Music off';sound.setAttribute('aria-pressed',String(playing));sound.setAttribute('aria-label',playing?'Pause background music':'Play background music');}catch{playing=false;sound.textContent='Audio unavailable';sound.setAttribute('aria-pressed','false');}}
sound.addEventListener('click',()=>setMusic(!playing));
document.querySelector('.seal').addEventListener('click',()=>{document.body.classList.add('opened','experience-open');setMusic(true);setTimeout(()=>document.querySelector('#welcome').scrollIntoView({behavior:reduced?'instant':'smooth'}),reduced?0:900);});
document.addEventListener('visibilitychange',()=>{if(document.hidden&&playing)setMusic(false);});
let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const distance=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=`${distance>0?scrollY/distance*100:0}%`;if(scrollY>80)document.body.classList.add('opened');ticking=false;});},{passive:true});
