import {themes} from './themes.js?v=20260919-50';
const requestedTheme=new URLSearchParams(location.search).get('theme'),theme=themes.find(item=>item.slug===(requestedTheme||document.body.dataset.theme));if(!theme)throw new Error('Unknown invitation theme');
const params=new URLSearchParams(location.search),one=(params.get('one')||'Amelia').slice(0,24),two=(params.get('two')||'Adam').slice(0,24),dateValue=params.get('date')||'2027-06-29',venueValue=(params.get('venue')||'Four Seasons Hotel Bosphorus, Istanbul').slice(0,80),dateObject=new Date(`${dateValue}T12:00:00`),dateLong=Number.isNaN(dateObject.valueOf())?'Date to be announced':new Intl.DateTimeFormat('en-GB',{day:'numeric',month:'long',year:'numeric'}).format(dateObject),dateParts=Number.isNaN(dateObject.valueOf())?['Date','—','To be announced']:[dateObject.toLocaleDateString('en-GB',{weekday:'long'}),String(dateObject.getDate()).padStart(2,'0'),dateObject.toLocaleDateString('en-GB',{month:'long',year:'numeric'})];
const sets={
'royal-ivory':['1519741497674-611481863552','1511285560929-80b456fea0bc','1519225421980-715cb0215aed','1606800052052-a08af7148866','1523438885200-e635ba2c371e','1465495976277-4387d4b0e4a6'],
'sidi-bou-said':['1519225421980-715cb0215aed','1523438885200-e635ba2c371e','1511285560929-80b456fea0bc','1519741497674-611481863552','1522673607200-164d1b6ce486','1537633552985-df8429e8048b'],
'midnight-gold':['1507504031003-b417219a0fde','1465495976277-4387d4b0e4a6','1511285560929-80b456fea0bc','1537633552985-df8429e8048b','1519741497674-611481863552','1523438885200-e635ba2c371e'],
'andalusian-palace':['1511285560929-80b456fea0bc','1522673607200-164d1b6ce486','1519225421980-715cb0215aed','1519741497674-611481863552','1606800052052-a08af7148866','1465495976277-4387d4b0e4a6'],
'rose-garden':['1517841905240-472988babdf9','1519741497674-611481863552','1519225421980-715cb0215aed','1523438885200-e635ba2c371e','1606800052052-a08af7148866','1465495976277-4387d4b0e4a6'],
'olive-estate':['1544078751-58fee2d8a03b','1519225421980-715cb0215aed','1511285560929-80b456fea0bc','1522673607200-164d1b6ce486','1519741497674-611481863552','1606800052052-a08af7148866'],
'bordeaux-velvet':['1465495976277-4387d4b0e4a6','1507504031003-b417219a0fde','1519741497674-611481863552','1511285560929-80b456fea0bc','1606800052052-a08af7148866','1523438885200-e635ba2c371e'],
'pearl-minimal':['1523438885200-e635ba2c371e','1519741497674-611481863552','1519225421980-715cb0215aed','1606800052052-a08af7148866','1511285560929-80b456fea0bc','1522673607200-164d1b6ce486'],
'desert-sunset':['1522673607200-164d1b6ce486','1511285560929-80b456fea0bc','1519741497674-611481863552','1544078751-58fee2d8a03b','1606800052052-a08af7148866','1519225421980-715cb0215aed'],
'celestial-blue':['1537633552985-df8429e8048b','1519741497674-611481863552','1507504031003-b417219a0fde','1519225421980-715cb0215aed','1606800052052-a08af7148866','1523438885200-e635ba2c371e']};
const titles={'royal-ivory':['A gilded promise','Baroque romance'],'sidi-bou-said':['Under Mediterranean skies','Porcelain & sea'],'midnight-gold':['Written in the stars','Midnight ceremony'],'andalusian-palace':['A palace of two hearts','Moorish romance'],'rose-garden':['Where love is in bloom','Botanical romance'],'olive-estate':['Rooted in love','An estate celebration'],'bordeaux-velvet':['A night in velvet','Candlelit romance'],'pearl-minimal':['Simply, forever','Modern editorial'],'desert-sunset':['Golden hour, forever','Desert bloom'],'celestial-blue':['To the moon and back','A celestial promise']};
const imageUrl=id=>`https://images.unsplash.com/photo-${id}?auto=format&fit=crop&w=1400&q=86`,photos=(sets[theme.slug]||theme.photoIds).map(imageUrl),[headline,collection]=titles[theme.slug]||[theme.note.split(' · ')[0],`${theme.category} collection`];
document.body.className=`${theme.slug} ${theme.kind} ${theme.dark?'dark':''}`;for(const [key,value]of Object.entries({paper:theme.paper,ink:theme.color,accent:theme.accent}))document.body.style.setProperty(`--${key}`,value);document.title=`${theme.name} — Invitation preview | AuraWeddings`;
const root=document.querySelector('#invitation');root.innerHTML=`
<div class="progress"></div><div class="invitation-gate" role="dialog" aria-modal="true" aria-label="Open wedding invitation"><div class="gate-atmosphere"><i></i><i></i><i></i><i></i><i></i></div><div class="opening-card"><div class="opening-art"><img src="${photos[0]}" alt="Amelia and Adam"><span class="opening-monogram">A <i>&amp;</i> A</span></div><div class="opening-copy"><span class="card-kicker">Together with their families</span><p class="save-date">Save the date</p><h1>Amelia <i>&amp;</i> Adam</h1><span class="opening-ornament">❦</span><time>29 · 06 · 2027</time><button class="open-card"><span>Open invitation</span><b>↘</b></button></div><span class="ribbon ribbon-one"></span><span class="ribbon ribbon-two"></span><span class="theme-flower flower-one"></span><span class="theme-flower flower-two"></span></div><p class="gate-instruction">Tap to open our wedding invitation</p></div>
<header class="topbar"><a href="/aura-weddings#themes">← AuraWeddings</a><span>${theme.name} · DEMO</span></header>
<section class="hero-scene"><img class="hero-photo" src="${photos[0]}" alt="Amelia and Adam wedding portrait"><div class="hero-overlay"></div><div class="hero-frame"></div><div class="hero-copy"><p class="eyeline">${collection}</p><h1><span>Amelia</span><i>&amp;</i><span>Adam</span></h1><p class="hero-date">29 · June · 2027</p><p class="scroll-hint">Scroll to enter our story ↓</p></div></section>
<main class="invitation"><section class="portrait-intro scene reveal" data-reveal="split"><div class="portrait-stack"><img src="${photos[1]}" alt="Bride portrait"><img src="${photos[2]}" alt="Groom portrait"><span>&amp;</span></div><div class="portrait-names"><p>Amelia</p><i>with love</i><p>Adam</p></div></section>
<section class="ceremony scene reveal" data-reveal="rise"><p class="eyeline">Ceremony information</p><h2>${headline}</h2><div class="family-grid"><article><small>Mr. & Mrs.</small><h3>Charles & Rosalind</h3><p>joyfully announce the wedding<br>of their beloved daughter</p></article><span class="family-mark">A<br><i>&amp;</i><br>A</span><article><small>Mr. & Mrs.</small><h3>Matthew & Genevieve</h3><p>together with their son<br>invite you to celebrate</p></article></div><div class="ceremony-date"><span>Tuesday</span><b>29</b><span>June<br>2027</span></div><p class="ceremony-note">The ceremony will begin at six in the evening</p></section>
<section class="gallery-scene scene reveal" data-reveal="gallery"><p class="eyeline">Our photographs</p><h2>Moments before forever</h2><div class="gallery-stage">${photos.map((src,i)=>`<figure class="gallery-slide ${i===0?'active':''}" data-slide="${i}"><img src="${src}" alt="Wedding photograph ${i+1}" loading="${i<2?'eager':'lazy'}"><figcaption>${String(i+1).padStart(2,'0')} / ${String(photos.length).padStart(2,'0')}</figcaption></figure>`).join('')}<button class="gallery-prev" aria-label="Previous photograph">←</button><button class="gallery-next" aria-label="Next photograph">→</button></div><div class="gallery-dots">${photos.map((_,i)=>`<button class="${i===0?'active':''}" data-go="${i}" aria-label="Show photograph ${i+1}"></button>`).join('')}</div></section>
<section class="reception scene reveal" data-reveal="wipe"><div class="reception-card"><p class="eyeline">Reception information</p><h2>Dinner beneath the lights</h2><p class="reception-place">Four Seasons Hotel Bosphorus · Istanbul</p><div class="date-hero"><span>Tuesday</span><b>29</b><span>June<br>2027</span></div><div class="countdown"><div><b data-unit="days">—</b><span>Days</span></div><div><b data-unit="hours">—</b><span>Hours</span></div><div><b data-unit="minutes">—</b><span>Min</span></div><div><b data-unit="seconds">—</b><span>Sec</span></div></div><button class="rsvp-open">Confirm attendance</button></div></section>
<section class="venue scene reveal" data-reveal="split"><div class="venue-copy"><p class="eyeline">Wedding reception venue</p><h2>The garden<br><em>by the sea.</em></h2><h3>Four Seasons Hotel Bosphorus</h3><p>Çırağan Cad. No:28, Beşiktaş, Istanbul</p><div class="venue-actions"><a class="link-button" href="https://www.google.com/maps/dir/?api=1&destination=Four+Seasons+Hotel+Bosphorus+Istanbul" target="_blank" rel="noopener">Get directions ↗</a><a class="link-button ghost" href="https://www.google.com/calendar/render?action=TEMPLATE&text=Amelia+%26+Adam+Wedding&dates=20270629T150000Z/20270629T210000Z&location=Four+Seasons+Hotel+Bosphorus%2C+Istanbul" target="_blank" rel="noopener">Add to calendar</a></div></div><div class="map-frame"><iframe title="Map showing Four Seasons Hotel Bosphorus" src="https://www.google.com/maps?q=Four+Seasons+Hotel+Bosphorus+Istanbul&output=embed" loading="lazy" allowfullscreen></iframe><span class="map-pin">♡</span></div></section>
<section class="dress-schedule scene reveal" data-reveal="rise"><div class="dress"><p class="eyeline">Dress code</p><h2>Evening elegance</h2><div class="swatches"><i></i><i></i><i></i><i></i></div><p>Formal attire · warm neutrals welcome</p></div><div class="timeline"><p class="eyeline">Wedding day schedule</p><ol><li><time>18:00</time><span>Welcome</span></li><li><time>18:30</time><span>Ceremony</span></li><li><time>20:00</time><span>Dinner</span></li><li><time>21:30</time><span>First dance</span></li><li><time>00:00</time><span>Farewell</span></li></ol></div></section>
<section class="guestbook scene reveal" data-reveal="rise"><p class="eyeline">Guestbook</p><h2>Leave a little love</h2><form class="wish-form"><label><span>Your name</span><input name="name" required placeholder="Name"></label><label><span>Your wishes</span><textarea name="wish" required placeholder="Write a message for the couple"></textarea></label><button>Send wishes</button></form><div class="wishes"><blockquote>“The loveliest couple. Wishing you a lifetime of joy.”<cite>— Sophie</cite></blockquote><blockquote>“Save us a dance. We cannot wait to celebrate!”<cite>— Oliver & Charlotte</cite></blockquote></div></section>
<section class="gift scene reveal" data-reveal="bloom"><p class="eyeline">Gift box</p><button class="gift-box" aria-expanded="false"><span class="gift-lid"></span><span class="gift-body">A <i>&amp;</i> A</span></button><div class="gift-message"><h2>Your presence is our greatest gift.</h2><p>Thank you for being part of our story.</p></div></section>
<section class="closing scene reveal"><img src="${photos[5]}" alt="Wedding celebration"><div><p class="eyeline">With love</p><h2>We cannot wait<br>to celebrate with you.</h2><a class="link-button" href="/contact?service=auraweddings&theme=${theme.slug}">Choose ${theme.name} →</a></div></section></main>
<footer class="footer">An invitation by <a href="/aura-weddings">AuraWeddings</a> · ${theme.name}</footer><button class="sound" aria-pressed="false">♫ Music off</button>
<dialog class="rsvp-dialog"><button class="rsvp-close" aria-label="Close">×</button><p class="eyeline">RSVP</p><h2>Will you join us?</h2><form><label>Your name<input required placeholder="Full name"></label><label>Attendance<select><option>Joyfully accepts</option><option>Regretfully declines</option></select></label><label>Number of guests<input type="number" min="1" max="6" value="1"></label><button>Send RSVP</button></form><p class="rsvp-success" hidden>Thank you — your response has been received.</p></dialog>`;
if(params.size){
  const set=(selector,value)=>{const node=document.querySelector(selector);if(node)node.textContent=value};
  set('.opening-monogram',`${one[0]||'A'} & ${two[0]||'A'}`);set('.opening-copy h1',`${one} & ${two}`);set('.opening-copy time',dateLong);
  const heroNames=document.querySelectorAll('.hero-copy h1 span');if(heroNames.length>1){heroNames[0].textContent=one;heroNames[1].textContent=two}set('.hero-date',dateLong);
  const portraitNames=document.querySelectorAll('.portrait-names p');if(portraitNames.length>1){portraitNames[0].textContent=one;portraitNames[1].textContent=two}
  document.querySelectorAll('.ceremony-date,.date-hero').forEach(block=>{const spans=block.querySelectorAll('span');if(spans.length>1){spans[0].textContent=dateParts[0];spans[1].textContent=dateParts[2]}const day=block.querySelector('b');if(day)day.textContent=dateParts[1]});
  set('.reception-place',venueValue);set('.venue-copy h3',venueValue);set('.venue-copy>p',venueValue);
  const map=document.querySelector('.map-frame iframe');if(map){map.src=`https://www.google.com/maps?q=${encodeURIComponent(venueValue)}&output=embed`;map.title=`Map showing ${venueValue}`}
  const directions=document.querySelector('.venue-actions a');if(directions)directions.href=`https://www.google.com/maps/dir/?api=1&destination=${encodeURIComponent(venueValue)}`;
}
const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches,gate=document.querySelector('.invitation-gate');function openExperience(){if(document.body.classList.contains('experience-open'))return;document.body.classList.add('experience-open');gate?.setAttribute('aria-hidden','true');setMusic(true);setTimeout(()=>gate?.remove(),reduced?50:1700)}document.querySelector('.open-card').addEventListener('click',openExperience);addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!document.body.classList.contains('experience-open')){e.preventDefault();openExperience()}});
if(!reduced&&'IntersectionObserver'in window){document.body.classList.add('motion');const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('visible');observer.unobserve(entry.target)}}),{threshold:.12});document.querySelectorAll('.reveal').forEach(node=>observer.observe(node))}
let slide=0;const slides=[...document.querySelectorAll('.gallery-slide')],dots=[...document.querySelectorAll('[data-go]')];function showSlide(index){slide=(index+slides.length)%slides.length;slides.forEach((item,i)=>item.classList.toggle('active',i===slide));dots.forEach((item,i)=>item.classList.toggle('active',i===slide))}document.querySelector('.gallery-prev').addEventListener('click',()=>showSlide(slide-1));document.querySelector('.gallery-next').addEventListener('click',()=>showSlide(slide+1));dots.forEach(dot=>dot.addEventListener('click',()=>showSlide(Number(dot.dataset.go))));
const wedding=new Date(`${dateValue}T18:00:00+03:00`).getTime();function countdown(){let s=Math.max(0,Math.floor((wedding-Date.now())/1000));const u={days:Math.floor(s/86400),hours:Math.floor(s/3600)%24,minutes:Math.floor(s/60)%60,seconds:s%60};for(const[k,v]of Object.entries(u))document.querySelector(`[data-unit="${k}"]`).textContent=String(v).padStart(2,'0')}countdown();setInterval(countdown,1000);
const dialog=document.querySelector('.rsvp-dialog');function openRsvp(){dialog.classList.add('open');dialog.setAttribute('open','');document.body.classList.add('modal-open')}function closeRsvp(){dialog.classList.remove('open');dialog.removeAttribute('open');document.body.classList.remove('modal-open')}document.querySelector('.rsvp-open').addEventListener('click',openRsvp);document.querySelector('.rsvp-close').addEventListener('click',closeRsvp);dialog.addEventListener('click',e=>{if(e.target===dialog)closeRsvp()});dialog.querySelector('form').addEventListener('submit',e=>{e.preventDefault();e.target.hidden=true;dialog.querySelector('.rsvp-success').hidden=false});document.querySelector('.wish-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.target),q=document.createElement('blockquote'),c=document.createElement('cite');q.textContent=`“${d.get('wish')}”`;c.textContent=`— ${d.get('name')}`;q.append(c);document.querySelector('.wishes').prepend(q);e.target.reset()});document.querySelector('.gift-box').addEventListener('click',e=>{const b=e.currentTarget,o=b.classList.toggle('open');b.setAttribute('aria-expanded',String(o));document.querySelector('.gift-message').classList.toggle('open',o)});
let audio,master,timer,playing=false,step=0;const sound=document.querySelector('.sound'),notes=[0,7,12,16,14,12,7,4,0,7,12,19,16,14,12,7],base=196+themes.indexOf(theme)*4;function tone(){if(!audio||!playing)return;const now=audio.currentTime,osc=audio.createOscillator(),gain=audio.createGain();osc.type='sine';osc.frequency.value=base*Math.pow(2,notes[step++%notes.length]/12);gain.gain.setValueAtTime(0,now);gain.gain.linearRampToValueAtTime(.1,now+.03);gain.gain.exponentialRampToValueAtTime(.0001,now+2.4);osc.connect(gain);gain.connect(master);osc.start();osc.stop(now+2.5)}async function setMusic(on){try{if(on){const Audio=window.AudioContext||window.webkitAudioContext;if(!audio){audio=new Audio();master=audio.createGain();master.gain.value=.25;master.connect(audio.destination)}await audio.resume();playing=true;tone();clearInterval(timer);timer=setInterval(tone,680)}else{playing=false;clearInterval(timer);if(audio)await audio.suspend()}sound.textContent=playing?'Ⅱ Music on':'♫ Music off';sound.setAttribute('aria-pressed',String(playing))}catch{sound.textContent='Audio unavailable'}}sound.addEventListener('click',()=>setMusic(!playing));let ticking=false;addEventListener('scroll',()=>{if(ticking)return;ticking=true;requestAnimationFrame(()=>{const distance=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.width=`${distance>0?scrollY/distance*100:0}%`;ticking=false})},{passive:true});
