import {PACKAGES,FEATURES,COUNTRIES,calculateQuote} from './quote-model.js';
import {api,esc,money,pricing} from './ecosystem.js';
const build=document.querySelector('#websiteConfigurator'),intake=document.querySelector('#projectIntake');
const readFiles=async form=>{const files=[...form.elements.logo.files,...form.elements.attachments.files];if(files.length>3)throw new Error('Attach up to 3 files total.');return Promise.all(files.map(async file=>{if(file.size>500*1024||!['image/png','image/jpeg','image/webp','application/pdf'].includes(file.type))throw new Error('Use JPG, PNG, WebP or PDF, up to 500 KB per file.');const data=await new Promise((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(r.result.split(',')[1]);r.onerror=()=>reject(new Error('Could not read your file.'));r.readAsDataURL(file);});return {name:file.name,mime:file.type,data};}));};
const readClient=form=>Object.fromEntries(['name','company','email','whatsapp','industry','deadline','website','reference','description','budget'].map(name=>[name,form.elements[name].value.trim()]));
const params=new URLSearchParams(location.search);
let catalog,step=0,submissionKey=crypto.randomUUID(),submitting=false;
function config(){const fd=new FormData(build);return {product:'Website',package:fd.get('package'),pages:fd.get('pages'),design:fd.get('design'),features:fd.getAll('features'),country:fd.get('country')};}
function validStep(fieldset){for(const control of fieldset.querySelectorAll('input,select,textarea')){if(!control.checkValidity()){control.reportValidity();return false;}}return true;}
function showStep(index){step=index;build.querySelectorAll('[data-build-step]').forEach((el,i)=>el.hidden=i!==index);document.querySelectorAll('[data-step-label]').forEach((el,i)=>{el.classList.toggle('current',i===index);el.setAttribute('aria-current',i===index?'step':'false');});build.querySelector('[data-build-back]').hidden=index===0;build.querySelector('[data-build-next]').hidden=index===5;build.querySelector('[data-build-submit]').hidden=index!==5;if(index===5)renderReview();const heading=build.querySelector(`[data-build-step="${index}"] legend`);heading.tabIndex=-1;heading.focus({preventScroll:true});}
function renderQuote(){if(!catalog)return;const q=calculateQuote(config(),catalog);document.querySelector('[data-quote-summary]').innerHTML=`<span class="eyebrow">${q.state}</span><h2>${esc(PACKAGES[config().package])}</h2><div class="quote-amount">${money(q.amount,q.currency)}</div>${q.amount===null?`<p>Starting point: ${money(q.startingPrice,q.currency)}. Scope and integrations need a reviewed proposal.</p>`:''}<p>${q.delivery?`Estimated delivery: ${q.delivery[0]}–${q.delivery[1]} working days after content and deposit.`:'Delivery confirmed after scope review.'}</p><ul>${q.features.map(f=>`<li>${esc(FEATURES[f])}</li>`).join('')||'<li>Core responsive website</li>'}</ul><p>Payment stages: ${q.paymentStages.join('% / ')}%. Subject to your reviewed quote.</p><p>Hosting, domains, provider fees and taxes are clarified in the final quote.</p>`;}
function renderReview(){const c=config(),client=readClient(build),q=catalog?calculateQuote(c,catalog):null;const rows=[['Package',PACKAGES[c.package]],['Pages',c.pages],['Design',c.design],['Market',COUNTRIES[c.country].join(' · ')],['Features',q?.features.map(f=>FEATURES[f]).join(', ')||'Core website'],['Estimate',q?money(q.amount,q.currency):'Review required'],['Contact',`${client.name} · ${client.email}`],['Project description',client.description]];build.querySelector('[data-review]').innerHTML=rows.map(([k,v])=>`<div><dt>${esc(k)}</dt><dd>${esc(v)}</dd></div>`).join('');}
async function submit(form,configuration){const status=form.querySelector('[data-form-status]'),button=form.querySelector('button[type=submit]');if(submitting)return;submitting=true;button.disabled=true;status.classList.remove('error');status.textContent='Saving your project request…';try{const files=await readFiles(form);const result=await api('/api/projects',{method:'POST',body:JSON.stringify({submissionKey,client:readClient(form),configuration,files})});status.textContent=`Request received · ${result.id}\nYour brief is saved. ${result.email==='not_configured'?'Automatic email is currently unavailable. Contact hello@auradigitalworks.com with this ID for project access.':'Secure project access is queued for email. If it does not arrive, contact hello@auradigitalworks.com with this ID.'}`;const a=document.createElement('a');a.className='text-link';a.href=`/project/${result.id}`;a.textContent='Open project access →';status.after(a);form.querySelectorAll('input,select,textarea,button').forEach(el=>el.disabled=true);}catch(error){status.classList.add('error');status.textContent=error.name==='TimeoutError'?'The request timed out. Retry to check or save it safely; your request key stays the same.':error.message;button.disabled=false;}finally{submitting=false;}}
if(build){build.querySelector('[data-feature-options]').innerHTML=Object.entries(FEATURES).map(([key,label])=>`<label class="choice"><input type="checkbox" name="features" value="${key}"><span>${label}</span></label>`).join('');if(params.has('package')&&params.get('package') in PACKAGES)build.querySelector(`[name=package][value="${params.get('package')}"]`).checked=true;
 const summary=document.querySelector('[data-quote-summary]');pricing().then(data=>{catalog=data.catalog;build.elements.country.value=data.suggestedCountry;renderQuote();}).catch(()=>{summary.innerHTML='<h2>Live pricing unavailable</h2><p>Please try again later or send a brief from the contact page. We do not calculate a quote from stale prices.</p>';build.querySelector('[data-build-submit]').disabled=true;});
 build.addEventListener('input',renderQuote);build.addEventListener('change',renderQuote);build.querySelector('[data-build-next]').addEventListener('click',()=>{const current=build.querySelector(`[data-build-step="${step}"]`);if(validStep(current))showStep(Math.min(5,step+1));});build.querySelector('[data-build-back]').addEventListener('click',()=>showStep(Math.max(0,step-1)));
 build.addEventListener('submit',event=>{event.preventDefault();if(!catalog)return;for(let i=0;i<6;i++){const fieldset=build.querySelector(`[data-build-step="${i}"]`);const invalid=[...fieldset.querySelectorAll('input,select,textarea')].find(el=>!el.checkValidity());if(invalid){showStep(i);invalid.reportValidity();return;}}submit(build,config());});build.addEventListener('keydown',e=>{if(e.key==='Enter'&&e.target.tagName!=='TEXTAREA'&&step<5){e.preventDefault();build.querySelector('[data-build-next]').click();}});showStep(0);
}
if(intake){const productMap={auramenu:'AuraMenu','auramenu-custom':'AuraMenu',aurapops:'AuraPops',auraweddings:'AuraWeddings',dashboard:'Dashboard',nfc:'NFC',automation:'Automation'};const requested=params.get('service')||'';intake.elements.product.value=productMap[requested.toLowerCase()]||([...intake.elements.product.options].some(o=>o.value===requested)?requested:'Website');const context=['theme','design','template','one','two','date','venue'].map(k=>params.has(k)?`${k}: ${params.get(k)}`:'').filter(Boolean).join('\n');if(context)intake.elements.description.value=context;
 pricing().then(data=>intake.elements.country.value=data.suggestedCountry).catch(()=>{});
 intake.addEventListener('submit',e=>{e.preventDefault();if(!intake.reportValidity())return;submit(intake,{product:intake.elements.product.value,package:'system',pages:'1-3',design:'standard',features:[],country:intake.elements.country.value,context});});
}
