import {PACKAGES,COUNTRIES} from './quote-model.js';
import {api,esc,money,pricing} from './api.js';
export {api,esc,money,pricing} from './api.js';
const reduced=matchMedia('(prefers-reduced-motion:reduce)').matches;
const fine=matchMedia('(hover:hover) and (pointer:fine)').matches;
document.body.classList.add('page-enter');
// Accessible mobile menu behavior extends the shared legacy shell without duplicating its click listener.
const nav=document.querySelector('#navLinks'),menu=document.querySelector('#menuBtn');
const syncMenu=()=>{const open=menu?.getAttribute('aria-expanded')==='true';document.body.classList.toggle('menu-open',open);menu?.setAttribute('aria-label',open?'Close menu':'Open menu');if(open)nav?.querySelector('a')?.focus();};
menu?.addEventListener('click',syncMenu);
function closeMenu(){if(menu?.getAttribute('aria-expanded')==='true'){menu.click();menu.focus();}}
document.addEventListener('keydown',event=>{if(event.key==='Escape'){closeMenu();document.querySelectorAll('.nav-products[open]').forEach(el=>el.removeAttribute('open'));}if(event.key==='Tab'&&document.body.classList.contains('menu-open')){const nodes=[...nav.querySelectorAll('a,summary'),menu].filter(el=>el.getClientRects().length);const first=nodes[0],last=nodes.at(-1);if(event.shiftKey&&document.activeElement===first){last.focus();event.preventDefault();}else if(!event.shiftKey&&document.activeElement===last){first.focus();event.preventDefault();}}});
nav?.addEventListener('click',event=>{if(event.target.closest('a'))closeMenu();});
addEventListener('resize',()=>{if(innerWidth>900)closeMenu();});
document.addEventListener('click',event=>{if(!event.target.closest('.nav-products'))document.querySelectorAll('.nav-products[open]').forEach(el=>el.open=false);});
const studioFilm=document.querySelector('[data-studio-film]');
if(studioFilm&&!reduced&&!navigator.connection?.saveData&&innerWidth>=768){studioFilm.querySelectorAll('source[data-src]').forEach(source=>source.src=source.dataset.src);studioFilm.load();studioFilm.play().catch(()=>{});new IntersectionObserver(entries=>entries.forEach(e=>e.isIntersecting&&!document.hidden?studioFilm.play().catch(()=>{}):studioFilm.pause()),{threshold:.05}).observe(studioFilm);document.addEventListener('visibilitychange',()=>document.hidden?studioFilm.pause():studioFilm.getBoundingClientRect().bottom>0&&studioFilm.play().catch(()=>{}));}
const phone=document.querySelector('[data-ecosystem-phone]');
const phoneScenes={menu:['AURAMENU','Good food.<br>One scan.',['Chef’s selection','Seasonal menu','WhatsApp order']],pops:['AURAPOPS','Your world.<br>One tap.',['Instagram','Maps & reviews','Contact']],weddings:['AURAWEDDINGS','Amelia<br>&amp; Adam',['Our story','Save the date','RSVP']],web:['WEBSITES','Designed.<br>Connected.',['Your brand','Your services','Project request']],systems:['SYSTEMS','A clearer<br>workspace.',['Orders & clients','Payments','Notifications']],nfc:['NFC / QR','From card<br>to connection.',['Tap your card','Open your profile','Start a conversation']]};
function renderPhone(kind){if(!phone)return;const [label,title,items]=phoneScenes[kind];phone.dataset.product=kind;phone.innerHTML=`<span class="phone-caption">${label} · INTERFACE CONCEPT</span><h3>${title}</h3>${kind==='menu'?'<img src="/media/nfc-restaurant.webp" alt="Restaurant menu preview" width="450" height="300" loading="lazy">':''}${items.map(text=>`<div class="phone-item">${text}<span>↗</span></div>`).join('')}`;phone.style.transform=reduced?'none':'rotate(0deg)';}
const storyObserver=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){document.querySelectorAll('[data-product-step]').forEach(el=>el.classList.toggle('active',el===e.target));renderPhone(e.target.dataset.productStep);}}),{rootMargin:'-20% 0px -25% 0px',threshold:0});document.querySelectorAll('[data-product-step]').forEach(el=>storyObserver.observe(el));
const ctaObserver=new IntersectionObserver(entries=>entries.forEach(e=>e.target.style.setProperty('--cta-progress',e.isIntersecting?'1':'0')),{threshold:.2});if(!reduced)document.querySelectorAll('.cta-line').forEach(el=>{el.style.transition='transform .9s cubic-bezier(.16,1,.3,1)';ctaObserver.observe(el);});
if(fine&&!reduced)document.querySelectorAll('[data-card-tilt]').forEach(el=>{el.addEventListener('pointermove',e=>{const r=el.getBoundingClientRect();el.style.transform=`perspective(800px) rotateY(${((e.clientX-r.left)/r.width-.5)*8}deg) rotateX(${(.5-(e.clientY-r.top)/r.height)*8}deg)`;});el.addEventListener('pointerleave',()=>el.style.removeProperty('transform'));});
const tabs=document.querySelector('.destination-tabs'),dest=document.querySelector('[data-destination-preview]');
tabs?.addEventListener('click',e=>{const b=e.target.closest('[data-destination]');if(!b)return;tabs.querySelectorAll('button').forEach(el=>el.setAttribute('aria-pressed',String(el===b)));if(dest){dest.querySelector('h3').textContent=b.dataset.destination;dest.querySelector('.phone-caption').textContent='NFC DESTINATION PREVIEW';dest.querySelector('.phone-item').textContent=b.dataset.description||'One tap opens the destination you choose.';}});
document.querySelector('[data-tap-demo]')?.addEventListener('click',()=>{document.querySelector('[data-nfc-demo-card]')?.classList.toggle('is-tapped');if(dest)dest.querySelector('.phone-caption').textContent='TAP DEMO · PREVIEW OPENED';});
document.querySelectorAll('[data-work-filter]').forEach(button=>button.addEventListener('click',()=>{const type=button.dataset.workFilter;document.querySelectorAll('[data-work-filter]').forEach(b=>b.setAttribute('aria-pressed',String(b===button)));let visible=0;document.querySelectorAll('[data-case-type]').forEach(el=>{el.hidden=type!=='all'&&el.dataset.caseType!==type;if(!el.hidden)visible++;});document.querySelector('[data-work-empty]').hidden=visible>0;}));
const countrySelect=document.querySelector('[data-country-select]');
if(countrySelect){pricing().then(({catalog,suggestedCountry})=>{countrySelect.value=suggestedCountry;const update=()=>document.querySelectorAll('[data-package-price]').forEach(el=>el.textContent=money(catalog.prices[el.dataset.packagePrice][COUNTRIES[countrySelect.value][1]],COUNTRIES[countrySelect.value][1]));update();countrySelect.addEventListener('change',update);}).catch(()=>{document.querySelectorAll('[data-package-price]').forEach(el=>el.textContent='Request a quote');document.querySelector('[data-pricing-error]').textContent='Live pricing is temporarily unavailable. You can still contact us for a reviewed quote.';});}
// Make old product choice links useful with JavaScript disabled and keep focus within modal.
const modal=document.querySelector('#menuChoiceModal');let returnFocus;
if(modal){document.querySelectorAll('[data-menu-choice]').forEach(link=>link.addEventListener('click',()=>returnFocus=link));document.addEventListener('keydown',e=>{if(modal.hidden)return;if(e.key==='Tab'){const items=[...modal.querySelectorAll('a,button')].filter(el=>el.getClientRects().length);const first=items[0],last=items.at(-1);if(e.shiftKey&&document.activeElement===first){last.focus();e.preventDefault();}else if(!e.shiftKey&&document.activeElement===last){first.focus();e.preventDefault();}}});new MutationObserver(()=>{if(modal.hidden)returnFocus?.focus();}).observe(modal,{attributes:true,attributeFilter:['hidden']});}
// Avoid a second hardcoded assistant price list. Product responses are composed from the live settings.
api('/api/settings').then(settings=>{if(typeof chatCopy!=='undefined'&&settings){for(const lang of ['en','tr','ar']){chatCopy[lang].web='Use Build your website to see the current localized estimate: /build';chatCopy[lang].menu=`AuraMenu self-build: ${settings.auramenu_self_price} TRY. Managed setup starts at ${settings.qr_menu_price} TRY. Review the plan at /aura-menu.`;chatCopy[lang].nfc=`NFC cards start at ${settings.nfc_price} TRY. Design your card at /nfc-studio.`;}}}).catch(()=>{});

const envelope=document.querySelector('[data-envelope]');if(envelope){new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)envelope.classList.add('open');}),{threshold:.3}).observe(envelope);}
