import {api,esc,money} from './ecosystem.js';
import {PACKAGES,FEATURES,STATUSES} from './quote-model.js';
const host=document.querySelector('[data-project-portal]'),form=document.querySelector('#projectAccess');
const id=decodeURIComponent(location.pathname.split('/').at(-1));
if(/^AD-[A-Z0-9-]+$/.test(id))form.elements.id.value=id;
const fragment=new URLSearchParams(location.hash.slice(1));
const access=fragment.get('access');if(access)history.replaceState(null,'',location.pathname+location.search);
async function load(){try{if(access)await api(`/api/projects/${id}/session`,{method:'POST',body:JSON.stringify({token:access})});const {project:p}=await api(`/api/projects/${id}`);const q=p.quote;host.innerHTML=`<div class="project-grid"><section class="card"><span class="eyebrow">${esc(p.id)}</span><h2>${esc(p.client.company||p.client.name)}</h2><p><button type="button" class="btn btn-ghost" data-portal-logout>Sign out</button></p><p>${esc(p.configuration.product)} · ${esc(PACKAGES[p.configuration.package])}</p><dl class="review-grid"><div><dt>Status</dt><dd>${esc(p.status)}</dd></div><div><dt>Quote</dt><dd>${money(q.amount,q.currency)}</dd></div><div><dt>Paid</dt><dd>${money(p.paid,q.currency)}</dd></div><div><dt>Remaining</dt><dd>${money(q.amount===null?null:Math.max(0,q.amount-p.paid),q.currency)}</dd></div><div><dt>Payment stages</dt><dd>${q.paymentStages.join('% / ')}%</dd></div><div><dt>Features</dt><dd>${q.features.map(f=>esc(FEATURES[f])).join(', ')||'Core website'}</dd></div></dl>${p.paymentUrl?`<a class="btn btn-primary" href="${esc(p.paymentUrl)}" target="_blank" rel="noopener noreferrer">Open secure payment ↗</a>`:'<p>A payment action appears once your provider link is ready.</p>'}${p.previewUrl?`<p><a class="text-link" href="${esc(p.previewUrl)}" target="_blank" rel="noopener noreferrer">Open project preview ↗</a></p>`:''}</section><section class="card"><h2>Project timeline</h2><ol class="timeline">${p.timeline.map(e=>`<li><strong>${esc(e.status)}</strong><small>${esc(e.created_at)} UTC</small></li>`).join('')}</ol><p>Next stages: ${STATUSES.slice(STATUSES.indexOf(p.status)+1).map(esc).join(' → ')}</p></section><section class="card"><h2>Your files</h2>${p.files.length?p.files.map(f=>`<p><a class="text-link" href="/api/projects/${esc(p.id)}/files/${esc(f.id)}">${esc(f.name)} ↓</a></p>`).join(''):'<p>No files attached.</p>'}</section><section class="card"><h2>Need to discuss it?</h2><p>Reply to your project email or contact the studio. Include ${esc(p.id)} so we can find your project.</p><a class="text-link" href="mailto:hello@auradigitalworks.com?subject=${encodeURIComponent(p.id)}">Email the studio ↗</a></section></div>`;document.querySelector('[data-portal-logout]')?.addEventListener('click',async()=>{await api('/api/projects/logout',{method:'POST'});location.reload();});}catch(error){document.querySelector('[data-portal-notice]').textContent=error.status===401?'Use the private link sent to your project email, or request a new link below.':'We could not load the project. Please try again or contact the studio.';}}
form.addEventListener('submit',async e=>{e.preventDefault();const status=form.querySelector('[role=status]'),button=form.querySelector('button');button.disabled=true;try{const result=await api('/api/projects/access',{method:'POST',body:JSON.stringify({id:form.elements.id.value.trim(),email:form.elements.email.value.trim()})});status.textContent=result.message;}catch(error){status.textContent=error.message;}finally{button.disabled=false;}});
if(/^AD-[A-Z0-9-]+$/.test(id))load();else document.querySelector('[data-portal-notice]').textContent='Enter the project ID and email used for your request.';
